
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: nonochais

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update