
server:
  port: 8082

client:
  service:
    url: http://localhost:8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: nonochais
  mail:
    host: smtp.gmail.com
    port: 587
    username: source_mail@gmail.com   #change for the source email address
    password: password                #change for the account application password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: ms.movie

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: RECORD
    topic-rent: rent-movie
    group-rent: rent-consumer
    topic-return: return-movie
    group-return: return-consumer